[package]
name = "stremio-core-web"
version = "0.44.18"
authors = ["Smart Code OOD"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true
opt-level = 's'

[dependencies]
stremio-core = { git = "https://github.com/unclekingpin/stremio-core", branch = "override-meta-details-selected" }
stremio-derive = { git = "https://github.com/unclekingpin/stremio-core", branch = "override-meta-details-selected" }
stremio-analytics = { git = "https://github.com/unclekingpin/stremio-core", branch = "override-meta-details-selected" }
serde = { version = "1.0.*", features = ["derive"] }
serde_json = "1.0.*"
futures = "0.3.*"
http = "0.2.*"
url = { version = "2.2.*", features = ["serde"] }
chrono = "0.4.*"
semver = { version = "1", features = ["serde"] }
regex = "1.8"
hex = "0.4.*"
either = "1.6.*"
lazy_static = "1.4.*"
enclose = "1.1.*"
itertools = "0.10.*"
boolinator = "2.4.*"
Inflector = "0.11.*"
wasm-bindgen = { version = "=0.2.78", features = ["serde-serialize"] }
wasm-bindgen-futures = "0.4.*"

# panic hook for wasm
console_error_panic_hook = "0.1.*"

js-sys = "0.3.*"
web-sys = { version = "0.3.*", features = [
    "WorkerGlobalScope",
    "WorkerNavigator",
    "Request",
    "RequestInit",
    "Response",
    "console",
] }
getrandom = { version = "0.2.*", features = ["js"] }
cfg-if = "1.0"
serde_path_to_error = "0.1.*"

# Tracing
tracing = "0.1"
tracing-wasm = "0.2"

# A way to quickly test with local version of `core` crates
# [patch.'https://github.com/Stremio/stremio-core']

# stremio-core = { path = "../core" }
# stremio-derive = { path = "../core/stremio-derive" }
# stremio-analytics = { path = "../core/stremio-analytics" }
