name: Rust build

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v1
        - name: Build
          run: |
            mkdir -p build
            mkdir -p static
            eval "$(ssh-agent -s)"
            ssh-keygen -t rsa -b 4096 -f ~/.ssh/id_rsa -N ""
            ssh-add ~/.ssh/id_rsa
            ssh-add -L
            cat ~/.gitconfig
            rustup default nightly
            cargo --version
            cargo install wasm-pack
            yarn install
            yarn build
